# Generated by Django 4.1.7 on 2024-02-12 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_remove_wish_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wish',
            name='product',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
