# Generated by Django 4.1.7 on 2024-02-12 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_wish_owner_wish_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='owner',
        ),
        migrations.AddField(
            model_name='wish',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
